modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="catapults"
version="1.0.0"
displayName="catapults"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="janko, MCreator"

[[dependencies.catapults]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




